# utils/disease_info.py

DISEASE_INFO = {
    'Cerscospora': {
        'name': 'Cercospora Leaf Spot',
        'name_am': 'ሰርኮስፖራ የቅጠል ነጠብጣብ',
        'name_om': 'Tuqaa Baalaa Cerkosoporaa',
        'description': 'Caused by fungus Cercospora coffeicola. Brown spots with gray centers on leaves.',
        'description_am': 'በሰርኮስፖራ ኮፊኢኮላ በሚባል ፈንገስ የሚመጣ። ቡናማ ነጠብጣቦች ከግራጫ መሃል ጋር።',
        'description_om': 'Fungus Cercospora coffeicola jedhamuun kan dhufu. Tuqaa diimaa fi gidduu callaa ta’e qaba.',
        'treatment': 'Apply appropriate fungicides. Improve air circulation and sunlight penetration.',
        'treatment_am': 'ተገቢ ፈንገስ ተዋጊ ይጠቀሙ። የአየር ዝውውር እና የፀሀይ ብርሀን መግባት ያሻሽሉ።',
        'treatment_om': 'Qoricha Fagaa ta’e fayyadami. Naannoo Bubbisaa fi akka Ifa Galantu gochi.',
        'prevention': 'Proper pruning, balanced fertilization, shade management.',
        'prevention_am': 'ትክክለኛ ቅርንጫፍ መቁረጥ፣ ሚዛናዊ ማዳበሪያ፣ ጥላ አያያዝ።',
        'prevention_om': 'Muriin sirrii ta’e, xaa’oo qindeessuu, gaaddisa to’achuu.',
        'severity': 'Moderate',
        'severity_am': 'መካከለኛ',
        'severity_om': 'Giddu galeessa',
        'icon': '🍂'
    },
    'Healthy': {
        'name': 'Healthy',
        'name_am': 'ጤናማ',
        'name_om': 'Fayyaa qaba',
        'description': 'The coffee leaf appears healthy with no signs of disease or pest damage.',
        'description_am': 'የቡና ቅጠሉ ምንም አይነት የበሽታ ወይም የተባይ ጉዳት ሳይታይበት ጤናማ ሆኖ ቀርቧል።',
        'description_om': 'Baalli Bunaa kuni fayyaa qaba; mallattoo dhukkubaa ykn miidhaa ilbiisaa hin argisiisu.',
        'treatment': 'No treatment needed. Continue regular monitoring.',
        'treatment_am': 'ምንም አይነት ህክምና አያስፈልግም። መደበኛ ክትትል ይቀጥሉ።',
        'treatment_om': 'Qorichoon hin barbaachisu. To’annoo yeroo yeroon itti fufaa.',
        'prevention': 'Maintain proper nutrition, irrigation, and regular inspection.',
        'prevention_am': 'ትክክለኛ አመጋገብ፣ መስኖ እና መደበኛ ምርመራ ይኑር።',
        'prevention_om': 'Xaa’oo sirrii, obaasuu fi qorannoo yeroo yeroon eeggadhu.',
        'severity': 'None',
        'severity_am': 'ምንም',
        'severity_om': 'Homtuu',
        'icon': '✅'
    },
    'Leaf_rust': {
        'name': 'Coffee Leaf Rust',
        'name_am': 'የቡና ዝገት',
        'name_om': 'Dhulluun Bunaa',
        'description': 'Caused by fungus Hemileia vastatrix. Yellow-orange powdery spots on leaf undersides.',
        'description_am': 'በሄሚሌያ ቫስታትሪክስ በሚባል ፈንገስ የሚመጣ። በቅጠሉ በታችኛው ክፍል ላይ ቢጫ-ብርቱካናማ ዱቄት የሚመስል ነጠብጣብ።',
        'description_om': 'Fungus Hemileia vastatrix jedhamuun kan dhufu. Tuqaa daaduu-birtukaanaa gadi fageenya irratti.',
        'treatment': 'Apply copper-based fungicides. Remove and destroy infected leaves.',
        'treatment_am': 'መዳብ መሰረት ያደረጉ ፈንገስ ተዋጊዎችን ይጠቀሙ። በበሽታው የተጠቁትን ቅጠሎች አስወግደው ያጥፉ።',
        'treatment_om': 'Qoricha Nyaata Koopirii irratti hundaa’e fayyadami. Baalota dhukkubiin qabame balleessi.',
        'prevention': 'Use resistant varieties, maintain proper spacing, avoid overhead irrigation.',
        'prevention_am': 'ተከላካይ ዝርያዎችን ይጠቀሙ፣ ትክክለኛ ክፍተት ይስጡ፣ ከላይ መስኖ ማስወገድ።',
        'prevention_om': 'Gosoota ofirraa ittisuu danda’an fayyadami, addaan fageenya sirrii eeggadhu, bishaan irraa obaasuu irraa of qusadhu.',
        'severity': 'High',
        'severity_am': 'ከፍተኛ',
        'severity_om': 'Olaanaa',
        'icon': '⚠️'
    },
    'Miner': {
        'name': 'Coffee Leaf Miner',
        'name_am': 'የቡና ቆፋሪ',
        'name_om': 'Xuuxxuu Bunaa',
        'description': 'Damage caused by coffee leaf miner larvae (Leucoptera coffeella). Serpentine mines in leaves.',
        'description_am': 'በቡና ቅጠል ቆፋሪ እጮች (ሉኮፕተራ ኮፊኤላ) የሚደርስ ጉዳት። በቅጠሎች ላይ እባብ ቅርጽ ያለው ቀያደድ።',
        'description_om': 'Miidhaan ilbiisa Xuuxxuu Bunaa (Leucoptera coffeella) jedhamuun kan dhufu. Kotta baala keessatti bofa fakkaatu uuma.',
        'treatment': 'Apply neem oil or appropriate insecticides. Biological control with natural enemies.',
        'treatment_am': 'የኒም ዘይት ወይም ተገቢ ፀረ-ተባይ መድሀኒት ይጠቀሙ። በተፈጥሮ ጠላቶች ባዮሎጂካል ቁጥጥር።',
        'treatment_om': 'Zayitii Neem ykn qoricha ilbiisaa ta’e fayyadami. Geggeessuu baayoloojikaalii diinota uumamaan ta’aniin.',
        'prevention': 'Regular monitoring, maintain tree vigor, avoid water stress.',
        'prevention_am': 'መደበኛ ክትትል፣ የዛፉን ጥንካሬ መጠበቅ፣ የውሃ እጥረትን ማስወገድ።',
        'prevention_om': 'To’annoo yeroo yeroon, jabina muka eeggadhu, dhabina bishaan irraa of qusadhu.',
        'severity': 'Moderate',
        'severity_am': 'መካከለኛ',
        'severity_om': 'Giddu galeessa',
        'icon': '🐛'
    },
    'Phoma': {
        'name': 'Phoma Leaf Spot',
        'name_am': 'ፎማ የቅጠል ነጠብጣብ',
        'name_om': 'Tuqaa Baalaa Foomawwan',
        'description': 'Caused by fungus Phoma costarricensis. Dark brown to black lesions on leaves.',
        'description_am': 'በፎማ ኮስታሪከንሲስ በሚባል ፈንገስ የሚመጣ። በቅጠሎች ላይ ጥቁር ቡናማ እስከ ጥቁር ቁስሎች።',
        'description_om': 'Fungus Phoma costarricensis jedhamuun kan dhufu. Madaa diimaa-gurraacha illee baala irratti.',
        'treatment': 'Remove infected leaves. Apply protective fungicides.',
        'treatment_am': 'በበሽታው የተጠቁትን ቅጠሎች ያስወግዱ። መከላከያ ፈንገስ ተዋጊ ይጠቀሙ።',
        'treatment_om': 'Baalota dhukkubiin qabame balleessi. Qoricha fagaa ittisa fayyadami.',
        'prevention': 'Avoid wounding plants, maintain proper nutrition.',
        'prevention_am': 'እጽዋትን ከመጉዳት ይቆጠቡ፣ ትክክለኛ አመጋገብ ይኑር።',
        'prevention_om': 'Muka miidhuu irraa of qusadhu, xaa’oo sirrii eeggadhu.',
        'severity': 'Moderate',
        'severity_am': 'መካከለኛ',
        'severity_om': 'Giddu galeessa',
        'icon': '🍂'
    }
}