[server]
enableStaticServing = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#27ae60"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"